### ISSUE TITLE
Application goes in background?

### ISSUE THREAD

**Issue by ghost** [yanzhenjie/AndPermission#111]
Hello, I'm Jaydip. And I use your lib for as permission and when I open permission dialog at that time application is going in background and after allow or deny permission application come in foreground.

I register my activity lifecycle callback in Application class.

Tell me what is the issue with it?

Thank You,
Jaydip

**Comment by yanzhenjie** [comment]
I have not tried applying permissions in `Application`, but I guess it is not possible， because the application has not really started.
The permission action must rely on `Activity`, so if the application **Apply For Permission** in `Application` is unreasonable, we can **Apply For Permission** in the `WelcomeActivity`, and apply a transparent theme to `WelcomActivity`, and apply for permission. Visual effects we will think that the application has not started.

**Comment by jaydipnumbertank** [comment]
Do you have any best example for use ActivityLifecycle? May be issue with my ActivityLifecycle.

**Comment by tabish075** [comment]
Try this for ActivityLifecycle to detect app is in  background or foreground: https://stackoverflow.com/a/13809991/8311441
